kind: pipeline
type: kubernetes
name: default

trigger:
  event:
  - push
  - pull_request
  - tag
  - promote
  - rollback
  - custom
steps:
  - name: docker ci
    image: plugins/docker
    settings:
      mtu: 1400
      mirror: https://jtkrmusq.mirror.aliyuncs.com
      username: 
        from_secret: docker_user_name
      password: 
        from_secret: docker_pass
      repo: registry.cn-hangzhou.aliyuncs.com/pivotstudio/raft
      registry: registry.cn-hangzhou.aliyuncs.com
      tags:
        - latest
        - build-${DRONE_BUILD_NUMBER} 
    when:
      event:
      - tag
      - promote
  - name: k8s cd
    image: bh90210/dron8s:latest
    depends_on:
      - "docker ci"
    settings:
      yaml: deploy/k8s.yaml
      build_tag: build-${DRONE_BUILD_NUMBER}
    when:
      event:
      - tag
      - promote