apiVersion: v1
kind: PersistentVolume
metadata:
  name: kvrf-pv-0
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: 172.16.0.18
    path: "/mnt/kvrf/1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kvrf-pv-1
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: 172.16.0.18
    path: "/mnt/kvrf/2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kvrf-pv-2
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  nfs:
    server: 172.16.0.18
    path: "/mnt/kvrf/3"